apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend-api
  labels:
    app: my-backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-backend-api
  template:
    metadata:
      labels:
        app: my-backend-api
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: my-backend-api
        image: andyy5/my-backend-api
---
apiVersion: v1
kind: Service
metadata:
  name: my-backend-api
  labels:
    app: my-backend-api
spec:
  type: ClusterIP
  ports:
  - port: 85
    protocol: TCP
    targetPort: 85
  selector:
    app: my-backend-api
